version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

# Define the jobs we want to run for this project
jobs:
  build_and_nox:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      # - restore_cache:
      #     # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip
      # - python/install-packages:
      #     pip-dependency-file: dev-requirements.txt
      #     pkg-manager: pip
      - python/install-packages:
          args: poetry
          pkg-manager: pip
          pypi-cache: true
      - python/install-packages:
          args: poetry
          pkg-manager: nox
          pypi-cache: true
      - run:
          name: Noxing the codebase
          command: |
            poetry add -D coverage
            poetry add -D pytest
            poetry add -D flake8 flake8-bugbear
            poetry add -D mypy
            poetry add -D --allow-prereleases black
            nox

# Orchestrate our job run sequence
workflows:
  nox_and_deploy:
    jobs:
      - build_and_nox
